export const HERO_DATA_LOADING = 'HERO_DATA_LOADING'
export const GET_CHARACTERS = 'GET_CHARACTERS'
export const GET_CHARACTER = 'GET_CHARACTER'

export const STARSHIP_DATA_LOADING = 'STARSHIP_DATA_LOADING'
export const GET_STARSHIPS = 'GET_STARSHIPS'
export const GET_STARSHIP = 'GET_STARSHIP'

export const VEHICLE_DATA_LOADING = 'VEHICLE_DATA_LOADING'
export const GET_VEHICLES = 'GET_VEHICLES'
export const GET_VEHICLE = 'GET_VEHICLE'

export const SPECIES_DATA_LOADING = 'SPECIES_DATA_LOADING'
export const GET_SPECIES = 'GET_SPECIES'
export const GET_SPECIES_ITEM = 'GET_SPECIES_ITEM'

export const PLANET_DATA_LOADING = 'PLANET_DATA_LOADING'
export const GET_PLANETS = 'GET_PLANETS'
export const GET_PLANET = 'GET_PLANET'

export const FILM_DATA_LOADING = 'FILM_DATA_LOADING'
export const GET_FILMS = 'GET_FILMS'
export const GET_FILM = 'GET_FILM'

export const GLOBAL_SUCCESS = 'GLOBAL_SUCCESS'
export const GLOBAL_ERROR = 'GLOBAL_ERROR'
export const CLEAR_TOAST = 'CLEAR_TOAST'
