export const HERO_DATA_LOADING = 'HERO_DATA_LOADING'
export const GET_HEROES = 'GET_HEROES'

export const STARSHIP_DATA_LOADING = 'STARSHIP_DATA_LOADING'
export const GET_STARSHIPS = 'GET_STARSHIPS'

export const VEHICLE_DATA_LOADING = 'VEHICLE_DATA_LOADING'
export const GET_VEHICLES = 'GET_VEHICLES'

export const SPECIES_DATA_LOADING = 'SPECIES_DATA_LOADING'
export const GET_SPECIES = 'GET_SPECIES'

export const PLANET_DATA_LOADING = 'PLANET_DATA_LOADING'
export const GET_PLANETS = 'GET_PLANETS'

export const FILM_DATA_LOADING = 'FILM_DATA_LOADING'
export const GET_FILMS = 'GET_FILMS'

export const GLOBAL_SUCCESS = 'GLOBAL_SUCCESS'
export const GLOBAL_ERROR = 'GLOBAL_ERROR'
export const CLEAR_TOAST = 'CLEAR_TOAST'
